# Generated by Django 6.0.5 on 2026-06-04 14:42

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lineas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrelinea', models.CharField(max_length=4, unique=True)),
                ('colorlinea', models.CharField(max_length=7, null=True)),
                ('imagenmicro', models.CharField(max_length=100, null=True)),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Linea',
                'verbose_name_plural': 'lineas',
                'db_table': 'lineas',
                'ordering': ['nombrelinea'],
            },
        ),
        migrations.CreateModel(
            name='Puntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordenada', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('descripcion', models.CharField(max_length=6)),
                ('stop', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name': 'punto',
                'verbose_name_plural': 'puntos',
                'db_table': 'puntos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LineaRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idruta', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)])),
                ('descripcion', models.CharField(max_length=17)),
                ('distancia', models.FloatField(default=0.0)),
                ('tiempo', models.FloatField(default=0.0)),
                ('idlinea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rutaslineas.lineas')),
            ],
            options={
                'verbose_name': 'lineasrutas',
                'db_table': 'lineasrutas',
                'ordering': ['idlinea', 'idruta'],
            },
        ),
        migrations.CreateModel(
            name='LineasPuntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('distancia', models.FloatField(default=0.0)),
                ('tiempo', models.FloatField(default=0.0)),
                ('idlinearuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rutaslineas.linearuta')),
                ('idpunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punto_origen', to='rutaslineas.puntos')),
                ('idpuntodest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='punto_destino', to='rutaslineas.puntos')),
            ],
            options={
                'verbose_name': 'lineapunto',
                'verbose_name_plural': 'lineaspuntos',
                'db_table': 'lineaspuntos',
                'ordering': ['idlinearuta', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='PuntosTransbordo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalizacionmin', models.IntegerField()),
                ('idlineadestino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trasbordo_destino', to='rutaslineas.linearuta')),
                ('idlineaorigen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trasbordo_origen', to='rutaslineas.linearuta')),
                ('idpunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rutaslineas.puntos')),
            ],
            options={
                'verbose_name': 'puntotrasbordo',
                'verbose_name_plural': 'puntostrasbordos',
                'db_table': 'puntostrasbordos',
                'ordering': ['idpunto'],
            },
        ),
    ]
