# Generated by Django 6.0.5 on 2026-06-12 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutaslineas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linearuta',
            options={'ordering': ['idlinea', 'idruta'], 'verbose_name': 'linearuta', 'verbose_name_plural': 'lineasrutas'},
        ),
    ]
